# site settings
title: Codo de Tenista
subtitle: by Grupo 7
Github: https://github.com/Biomedica-TallerDeProyectos-Grupo7
description: Página web del Grupo 7<br /> del curso Taller de Proyectos.
baseurl: "Biomedica-TallerDeProyectos-Grupo7.github.io" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 8

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
